### ISSUE TITLE
Support for non-integer named universes for branching reader

### ISSUE THREAD

**Issue by vvaltavi** [CORE-GATECH-GROUP/serpent-tools#318]
## Summary of issue

Serpent 2 allows universe names to be quite generic string literals. However, the branching reader of serpentTools only seems to support universe names that are integers.

This seems to be related to the int conversion on line 113 of serpentTools/parsers/branching.py (commit dd886ff):

`unvID, numVariables = [int(xx) for xx in self._advance()]`

Simply limiting the int conversion to numVariables reads the universe in without problems.

## Code for reproducing the issue

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import serpentTools

# --- Try to read in a .coe file with a non-integer universe name

serpentTools.read("./problematic.coe")
```

problematic.coe:
```
1 1 1 1 1
1 nom
3 VERSION 2.1.31 DATE 19/07/10 TIME 14:27:27
0 1 1
-u_SI_RR01 66
INF_FLX 2  5.74041E+14  3.00746E+13
INF_KINF 1  0.00000E+00
INF_REP_TIME 0
INF_PROMPT_LIFE 0
INF_TOT 2  5.78347E-01  1.28879E+00
INF_CAPT 2  3.99876E-03  9.30813E-02
INF_FISS 2  0.00000E+00  0.00000E+00
INF_NSF 2  0.00000E+00  0.00000E+00
INF_KAPPA 2  0.00000E+00  0.00000E+00
INF_INVV 2  5.83143E-08  2.27285E-06
INF_NUBAR 2  0.00000E+00  0.00000E+00
INF_ABS 2  3.99876E-03  9.30813E-02
INF_REMXS 2  7.45100E-03  1.03549E-01
INF_RABSXS 2  3.99876E-03  9.30813E-02
INF_CHIT 2  0.00000E+00  0.00000E+00
INF_CHIP 2  0.00000E+00  0.00000E+00
INF_CHID 2  0.00000E+00  0.00000E+00
INF_I135_YIELD 2  0.00000E+00  0.00000E+00
INF_XE135_YIELD 2  0.00000E+00  0.00000E+00
INF_XE135M_YIELD 2  0.00000E+00  0.00000E+00
INF_PM149_YIELD 2  0.00000E+00  0.00000E+00
INF_SM149_YIELD 2  0.00000E+00  0.00000E+00
INF_I135_MICRO_ABS 2  0.00000E+00  0.00000E+00
INF_XE135_MICRO_ABS 2  0.00000E+00  0.00000E+00
INF_XE135M_MICRO_ABS 2  0.00000E+00  0.00000E+00
INF_PM149_MICRO_ABS 2  0.00000E+00  0.00000E+00
INF_SM149_MICRO_ABS 2  0.00000E+00  0.00000E+00
INF_I135_MACRO_ABS 0
INF_XE135_MACRO_ABS 2  0.00000E+00  0.00000E+00
INF_XE135M_MACRO_ABS 2  0.00000E+00  0.00000E+00
INF_PM149_MACRO_ABS 0
INF_SM149_MACRO_ABS 2  0.00000E+00  0.00000E+00
INF_S0 4  5.70896E-01  3.51081E-03  4.01709E-03  1.18524E+00
INF_S1 4  6.95375E-02  4.69803E-04  9.90811E-05  1.36274E-01
INF_S2 4  2.99465E-02 -3.00374E-04  5.04317E-04  1.47021E-02
INF_S3 4  5.67487E-03 -1.63405E-04 -9.41070E-04  2.33707E-02
INF_S4 4 -6.29423E-04  1.48058E-05 -3.04844E-04  9.08625E-03
INF_S5 4 -8.77400E-04  5.21018E-05 -7.86868E-04  1.47220E-02
INF_S6 4 -1.00766E-03 -3.48433E-05  7.28146E-04  8.25812E-03
INF_S7 4  3.55102E-04  9.54221E-05 -1.89967E-04  3.26062E-03
INF_SP0 4  5.70896E-01  3.51081E-03  4.01709E-03  1.18524E+00
INF_SP1 4  6.95375E-02  4.69803E-04  9.90811E-05  1.36274E-01
INF_SP2 4  2.99465E-02 -3.00374E-04  5.04317E-04  1.47021E-02
INF_SP3 4  5.67487E-03 -1.63405E-04 -9.41070E-04  2.33707E-02
INF_SP4 4 -6.29423E-04  1.48058E-05 -3.04844E-04  9.08625E-03
INF_SP5 4 -8.77400E-04  5.21018E-05 -7.86868E-04  1.47220E-02
INF_SP6 4 -1.00766E-03 -3.48433E-05  7.28146E-04  8.25812E-03
INF_SP7 4  3.55102E-04  9.54221E-05 -1.89967E-04  3.26062E-03
INF_SCATT0 2  5.74407E-01  1.18926E+00
INF_SCATT1 2  7.00073E-02  1.36373E-01
INF_SCATT2 2  2.96461E-02  1.52065E-02
INF_SCATT3 2  5.51146E-03  2.24297E-02
INF_SCATT4 2 -6.14618E-04  8.78141E-03
INF_SCATT5 2 -8.25298E-04  1.39351E-02
INF_SCATT6 2 -1.04250E-03  8.98627E-03
INF_SCATT7 2  4.50524E-04  3.07065E-03
INF_SCATTP0 2  5.```
74407E-01  1.18926E+00
INF_SCATTP1 2  7.00073E-02  1.36373E-01
INF_SCATTP2 2  2.96461E-02  1.52065E-02
INF_SCATTP3 2  5.51146E-03  2.24297E-02
INF_SCATTP4 2 -6.14618E-04  8.78141E-03
INF_SCATTP5 2 -8.25298E-04  1.39351E-02
INF_SCATTP6 2 -1.04250E-03  8.98627E-03
INF_SCATTP7 2  4.50524E-04  3.07065E-03
INF_TRANSPXS 2  3.32000E-01  1.06608E+00
INF_DIFFCOEF 2  1.00402E+00  3.12672E-01
```

## Actual outcome including console output and error traceback if applicable

```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    serpentTools.read("./problematic.coe")
  File "/usr/local/lib/python3.6/dist-packages/serpentTools-0.7.0-py3.6.egg/serpentTools/parsers/__init__.py", line 155, in read
    returnedFromLoader.read()
  File "/usr/local/lib/python3.6/dist-packages/serpentTools-0.7.0-py3.6.egg/serpentTools/parsers/base.py", line 52, in read
    self._read()
  File "/usr/local/lib/python3.6/dist-packages/serpentTools-0.7.0-py3.6.egg/serpentTools/parsers/branching.py", line 48, in _read
    self._processBranchBlock()
  File "/usr/local/lib/python3.6/dist-packages/serpentTools-0.7.0-py3.6.egg/serpentTools/parsers/branching.py", line 75, in _processBranchBlock
    self._whereAmI['buIndx'])
  File "/usr/local/lib/python3.6/dist-packages/serpentTools-0.7.0-py3.6.egg/serpentTools/parsers/branching.py", line 113, in _processBranchUniverses
    unvID, numVariables = [int(xx) for xx in self._advance()]
  File "/usr/local/lib/python3.6/dist-packages/serpentTools-0.7.0-py3.6.egg/serpentTools/parsers/branching.py", line 113, in <listcomp>
    unvID, numVariables = [int(xx) for xx in self._advance()]
ValueError: invalid literal for int() with base 10: '-u_SI_RR01'
```

## Versions

* Version  from ``serpentTools.__version__``: 0.7.0 (commit dd886ff)

**Comment by drewejohnson** [comment]
Thanks for pointing this out! I'll have a fix out soon.
