### ISSUE TITLE
MicroXSReader _precheck errors out if no FYs have not been requested 

### ISSUE THREAD

**Issue by aalfonsi** [CORE-GATECH-GROUP/serpent-tools#464]
## Summary of issue
The MicroXSReader fails to read a ``mdx`` file if no fission yields are requested (in serpent simulation).
This is caused by the implementation in the ```_precheck``` method
## Code for reproducing the issue
see attachements

## Actual outcome including console output and error traceback if applicable

```
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:57:50) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from serpentTools import MicroXSReader
>>> r = MicroXSReader("a_mdx0_file_no_fy.m")
>>> r.read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alfoa/opt/miniconda3/envs/raptor/lib/python3.7/site-packages/serpentTools/parsers/base.py", line 47, in read
    self._precheck()
  File "/Users/alfoa/opt/miniconda3/envs/raptor/lib/python3.7/site-packages/serpentTools/parsers/microxs.py", line 188, in _precheck
    "found in {}".format(self.filePath))
serpentTools.messages.SerpentToolsException: Fission yields values were not found in a_mdx0_file_no_fy.m
```

## Versions

Please provide the following:

* Version  from ``serpentTools.__version__``: 0.9.4
* Python version - ``python --version``: 3.7.12
* IPython or Jupyter version if applicable: n/a
* If using the development version, the output from ``git describe``: n/a
[testXS.serpent.i_mdx0.txt](https://github.com/CORE-GATECH-GROUP/serpent-tools/files/9275530/testXS.serpent.i_mdx0.txt)
![errorSerpentTools](https://user-images.githubusercontent.com/26668536/183260440-97cd9718-6df1-4cea-bb95-583d35fc4b2d.png)

**Comment by aalfonsi** [comment]
if line  https://github.com/CORE-GATECH-GROUP/serpent-tools/blob/f61cd104bd997aa80429f1059bbc3669adc18654/serpentTools/parsers/microxs.py#L185
is replaced with:
```if 'NFY' in tline or 'XS_' in tline:```

the ```_precheck``` is still fulfilling its scope but with the flexibility to load XS-only files
